### ISSUE TITLE
Broken in Developer Edition

### ISSUE THREAD

**Issue by Mathnerd314** [fred-wang/webextension-mathml-copy#6]
The recent update broke copying in Developer Edition; e.g. go to http://asciimath.org/ and try to copy one of the formulas.

I have this error in my browser console:
```
Error: Attempt to postMessage on disconnected port  get-mathml-data.js:60:3
```

Also, why did the two menu items turn into into a 2-item menu?
And this is apparently a complete rewrite of the extension? You could at least have called it 2.0 rather than 1.3.1.
Furthermore homepage_url in manifest.json is wrong.

For now I've just gone back to 1.3, I'm not sure if AMO lets you revoke updates but otherwise I would recommend putting out a 1.3.2 and putting this on a beta channel.

**Comment by fred-wang** [comment]
@Mathnerd314 Thanks for the report.  Sorry about that, I had to rewrite all my 9 extensions during my spare time before the Mozille deadline and I'm not happy about it either. I'll investigate this when I have time but any help would be appreciated.

> Also, why did the two menu items turn into into a 2-item menu?

Yes, I know. Can you please open a separate issue for that? I'm afraid this is a limitation of WebExtension so we would need to ask Mozilla to extend their API, see https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contextMenus

> And this is apparently a complete rewrite of the extension? You could at least have called it 2.0 rather than 1.3.1.

Because it is not intended to have new features. Only changes due to WebExtensions limitations.

> Furthermore homepage_url in manifest.json is wrong.

It is correct. WebExtensions format is not specific to Mozilla, so the Github page is now the new home page.

> For now I've just gone back to 1.3, I'm not sure if AMO lets you revoke updates...

No they don't and they also do not allow to specify a minimal version. Also note that they will only allow WebExtensions in Firefox 57 (https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/).

**Comment by fred-wang** [comment]
The asciiMath pages works for me. However, https://developer.mozilla.org/en-US/docs/Mozilla/MathML_Project/MathML_Torture_Test has issues, probably because it is in iframe. Probably using browser.tabs.executeScript as was suggested on Mozilla help forum is not very reliable .

**Comment by Mathnerd314** [comment]
> Note that they will only allow WebExtensions in Firefox 57 (https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/).

Right, that's why I used Firefox Developer Edition, although now that I noticed it's [going](https://hacks.mozilla.org/2017/04/simplifying-firefox-release-channels/) [away](http://release.mozilla.org/firefox/release/2017/04/17/Dawn-Project-FAQ.html) I've switched back to Nightly again. [The plan](https://wiki.mozilla.org/Add-ons/Firefox57) seems to be that all types of extensions will still be allowed there, although disabled by default and only available under yet another pref. 

Anyways, it seems like 1.3.1 works on Nightly so this issue is only relevant for Developer Edition, or else is some interaction with one of my other addons; I might file another issue if it comes up, but for now this is resolved.

But I really like having two items in my context menu, so I'll keep using 1.3 and maybe the context menu issue will be resolved by the time Mozilla actually breaks an API instead of just annoying its users (haha).

> > Furthermore homepage_url in manifest.json is wrong.

> It is correct. WebExtensions format is not specific to Mozilla, so the Github page is now the new home page.

I meant that it is a 404. I think it should be https://github.com/fred-wang/webextension-mathml-copy/ instead of https://github.com/fred-wang/mathml-copy

**Comment by fred-wang** [comment]
OK, I'll still need to check why sometimes the copy & paste does not work...

**Comment by fred-wang** [comment]
@Mathnerd314 I just submitted a new 1.3.2 version for review. Hopefully, this improves the communication between background & content scripts. I have not tested on developer edition, though.
